name: basic-ci-test

on:
  push:

jobs:
  run-basic-test:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: pytest 설치
        run: pip install pytest

      - name: CI 기본 테스트 실행
        run: pytest test_basic_ci.py
